#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, r8f) uniform writeonly image2D ImageOut;
layout(binding = 1, r8f) uniform readonly image2D ImageIn;

void main() {
  uint row = (gl_GlobalInvocationID.x);
  uint col = (gl_GlobalInvocationID.y);
  float x = imageLoad(values, ivec2(row, col));
  imageStore(outputValues, ivec2(gl_GlobalInvocationID.xy), 1.f - x);
}